name: Laravel4-lang
pygments: true
slogan: Internationalization of Laravel 4
url: http://caouecs.github.io/Laravel4-lang/
title: Laravel4-lang
description: List of languages for Laravel4
google_analytics: 
show_downloads: true
theme: jekyll-theme-midnight